FinanceTracker/FinanceTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls')),
    path('account/', include('account.urls')),
    path('reports/', include('reports.urls'))
]

FinanceTracker/account/urls.py
from django.urls import path
from . import views
urlpatterns =[
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.CustomLoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.UserDashboardView.as_view(), name='dashboard'),
    path('account-info/', views.AccountInfoView.as_view(), name='account_info'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('initial-asset/', views.InitialAssetView.as_view(), name='initial_asset'),
]

FinanceTracker/transactions/urls.py
from . import views
from django.urls import path
urlpatterns =[
    path('', views.home, name='home'),
    path('transaction', views.TransactionView.as_view(), name='transaction'),
    path('add_account', views.AccountView.as_view(), name='add_account'),
    path('add_category', views.CategoryView.as_view(), name='add_category')
]

FinanceTracker/transactions/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    ACCOUNT_TYPES = (
        ('cash', 'نقدی'),
        ('card', 'کارت بانکی'),
    )
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, verbose_name="کاربر")
    name = models.CharField(max_length=100, verbose_name="نام حساب")
    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPES, verbose_name="نوع حساب")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")

    class Meta:
        verbose_name = "حساب مالی"
        verbose_name_plural = "حساب‌های مالی"

    def __str__(self):
        return f"{self.name} ({self.get_account_type_display()})"


class Category(models.Model):
    CATEGORY_TYPES = (
        ('income', 'درآمد'),
        ('expense', 'هزینه'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, verbose_name="کاربر")
    name = models.CharField(max_length=100, verbose_name="نام دسته‌بندی")
    type = models.CharField(max_length=10, choices=CATEGORY_TYPES, verbose_name="نوع")

    class Meta:
        verbose_name = "دسته‌بندی"
        verbose_name_plural = "دسته‌بندی‌ها"

    def __str__(self):
        return f"{self.name} ({self.get_type_display()})"


class Transaction(models.Model):
    TRANSACTION_TYPES = (
        ('income', 'درآمد'),
        ('expense', 'هزینه'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, verbose_name="کاربر")
    amount = models.IntegerField(verbose_name="مبلغ")
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPES, verbose_name="نوع تراکنش")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="دسته‌بندی")
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="حساب مالی")
    description = models.TextField(blank=True, verbose_name="توضیحات")
    date = models.DateTimeField(verbose_name="تاریخ تراکنش")
    receipt = models.ImageField(upload_to='receipts/', null=True, blank=True, verbose_name="تصویر رسید (اختیاری)")
    is_confirmed = models.BooleanField(default=False, verbose_name="تأیید شده؟")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="ایجاد در")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="به‌روزرسانی در")

    class Meta:
        verbose_name = "تراکنش"
        verbose_name_plural = "تراکنش‌ها"

    def __str__(self):
        return f"{self.transaction_type} - {self.amount} در {self.date.date()}"

FinanceTracker/transactions/forms.py
from django import forms
from . import models

class CreateTransactionForm(forms.ModelForm):
    class Meta:
        model = models.Transaction
        exclude = ['user']
        widgets ={
            'amount': forms.NumberInput(attrs={
                'class': 'form-control text-end',
                'placeholder': 'مثلاً ۵۰۰۰۰۰',
                'style': 'border-radius:10px; background:#f5f5f5; color:#111; border:1px solid #ccc;',
            }),

            'transaction_type': forms.Select(attrs={
                'class': 'form-select text-center',
                'style': 'border-radius:10px; background:#f5f5f5; border:1px solid #ccc;',
            }),

            'category': forms.Select(attrs={
                'class': 'form-select',
                'style': 'border-radius:10px; background:#f5f5f5; border:1px solid #ccc;',
            }),

            'account': forms.Select(attrs={
                'class': 'form-select',
                'style': 'border-radius:10px; background:#f5f5f5; border:1px solid #ccc;',
            }),

            'description': forms.Textarea(attrs={
                'rows': 3,
                'placeholder': 'توضیحات تراکنش (اختیاری)',
                'class': 'form-control',
                'style': 'border-radius:10px; background:#f5f5f5; border:1px solid #ccc;',
            }),

            'date': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': 'form-control',
                'style': 'border-radius:10px; background:#f5f5f5; border:1px solid #ccc;',
            }),

            'receipt': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'style': 'border-radius:10px; background:#fff; border:1px solid #ccc;',
            }),

            'is_confirmed': forms.CheckboxInput(attrs={
                'class': 'form-check-input',
                'style': 'transform: scale(1.2); margin-right:10px;',
            }),
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['category'].queryset = models.Category.objects.filter(user=user)
            self.fields['account'].queryset = models.Account.objects.filter(user=user)
            



class CreateAccountForm(forms.ModelForm):
    class Meta:
        model = models.Account
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)




class CreateCategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

FinanceTracker/transactions/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import CreateTransactionForm, CreateAccountForm, CreateCategoryForm
from .models import Transaction, Account, Category
from django.contrib.auth import get_user_model

User = get_user_model()

def home(request):
    return render(request, 'transactions/home.html')

class TransactionView(LoginRequiredMixin, FormView):
    model = Transaction
    template_name = 'transactions/createtransaction.html'
    form_class = CreateTransactionForm
    success_url = reverse_lazy('transaction')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        transaction = form.save(commit=False)

        user.save()
        transaction.user = user
        transaction.save()

        messages.success(self.request, "تراکنش با موفقیت ثبت شد.")
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class AccountView(LoginRequiredMixin, FormView):
    model = Account
    template_name = 'transactions/quick_add_account.html'
    form_class = CreateAccountForm
    success_url = reverse_lazy('transaction')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        account = form.save(commit=False)
        account.user = self.request.user
        account.save()
        return super().form_valid(form)


class CategoryView(LoginRequiredMixin, FormView):
    model = Category
    template_name = 'transactions/quick_add_category.html'
    form_class = CreateCategoryForm
    success_url = reverse_lazy('transaction')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        category = form.save(commit=False)
        category.user = self.request.user
        category.save()
        return super().form_valid(form)

FinanceTracker/transactions/templates/transactions/createtransaction.html
{% extends 'account/dashboard.html' %}

{% block dashboard_content %}
  <h2 class="text-2xl font-semibold mb-4">ثبت تراکنش</h2>

  <div class="card">
    <form method="post" class="space-y-4">
      {% csrf_token %}
      {% if form.non_field_errors %}
        <div class="bg-red-600 text-white p-3 rounded">
          {% for err in form.non_field_errors %}
            <div>{{ err }}</div>
          {% endfor %}
        </div>
      {% endif %}

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_amount">مبلغ:</label>
            {{ form.amount }}
            {% for error in form.amount.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="mb-3">
            <label for="id_transaction_type">نوع تراکنش:</label>
            {{ form.transaction_type }}
            {% for error in form.transaction_type.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="mb-3">
            <label for="id_category">دسته‌بندی:</label>
            {{ form.category }}
                     <a href="{% url 'add_category' %}" class="text-sm text-gray-400 mr-4">ساخت دسته بندی جدید</a>
            {% for error in form.category.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label for="id_account">حساب مالی:</label>
            {{ form.account }}
                     <a href="{% url 'add_account' %}" class="text-sm text-gray-400 mr-4">ساخت حساب مالی جدید</a>
            {% for error in form.account.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="mb-3">
            <label for="id_description">توضیحات:</label>
            {{ form.description }}
            {% for error in form.description.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="">
            <label for="id_date">تاریخ تراکنش:</label>
            {{ form.date }}
            {% for error in form.date.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="mb-3">
            <label for="id_receipt">تصویر رسید (اختیاری):</label>
            {{ form.receipt }}
            {% for error in form.receipt.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <div class="form-check mb-3">
            {{ form.is_confirmed }}
            <label for="id_is_confirmed" class="form-check-label">تأیید شده؟</label>
        </div>

        <button type="submit" class="btn-submit">ثبت تراکنش</button>
         <a href="{% url 'dashboard' %}" class="text-sm text-gray-400 mr-4">بازگشت به گزارش‌ها</a>
    </form>
</div>
</div>
{% endblock %}

FinanceTracker/transactions/templates/transactions/home.html
{% extends "base.html"%}
{% block content %}
<section class="landing-wrapper">
  <div class="container">
    <div class="intro-box">
        {% if user.is_authenticated %}
      <h1>سلام {{ user.first_name }}</h1>
      <p>دارایی شما اکنون {{ user.balance }}</p>
        {% else %}
      <div class="btn-group">
        <a href="" class="btn btn-primary">ورود</a>
        <a href="" class="btn btn-secondary">ثبت‌نام</a>
      </div>
        {% endif %}
    </div>

    <div class="features-box">
      <div class="feature-item">
        <a href="{% url 'dashboard' %}"><h3>📊 داشبورد کامل</h3></a>
        <p>نمایش دقیق درآمد، هزینه و موجودی حساب‌ها در یک نگاه.</p>
      </div>
      <div class="feature-item">
        <h3>🔔 یادآوری پرداخت‌ها</h3>
        <p>بدون استرس فراموش کردن پرداخت‌ها و قبض‌ها.</p>
      </div>
      <div class="feature-item">
        <h3>📈 گزارش‌گیری پیشرفته</h3>
        <p>تحلیل دقیق هزینه‌ها و درآمدها به صورت نموداری و قابل فهم.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

FinanceTracker/transactions/templates/transactions/quick_add_account.html
{% extends 'base.html' %}
{% block content %}

<h2 class="text-center mb-4">ثبت تراکنش جدید</h2>

<form method="post" novalidate>
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary w-100 mt-3">ثبت تراکنش</button>
</form>

{% endblock %}

FinanceTracker/transactions/templates/transactions/quick_add_category.html
{% extends 'base.html' %}
{% block content %}

<h2 class="text-center mb-4">ثبت دسته بندی جدید</h2>

<form method="post" novalidate>
    {% csrf_token %}
    
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary w-100 mt-3">ثبت</button>
</form>

{% endblock %}